### ISSUE TITLE
Hello, Yekeren!

### ISSUE THREAD

**Issue by fromSun2Moon** [yekeren/VCR-pretraining#2]
Dear keren! Thank you for your research! 

I'm a person who want to follow up your paper "VCR-shorcut".Last time, you upload modeling.py so I tried to run, but I encounter a problem.
Below is my log. I think some files(e.g. checkpoints) didn't exist. Could I get some files to run code please?
INFO:tensorflow:Restoring parameters from /workspace/language/language/question_answering/b2t2/uncased_L-12_H-768_A-12/model.ckpt-0
I1007 15:39:20.403484 140195579365184 saver.py:1284] Restoring parameters from /workspace/language/language/question_answering/b2t2/uncased_L-12_H-768_A-12/model.ckpt-0
2021-10-07 15:39:24.112935: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:183 : Not found: Key detection/adaptation/biases/Adam not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key detection/adaptation/biases/Adam not found in checkpoint
         [[{{node save/RestoreV2}}]]
  (1) Not found: Key detection/adaptation/biases/Adam not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_1001]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

I also have some questions.I look forward to running code about mlm and curriculum masking in paper (e.g. b2t2 mlm , cc46k)
I think b2t2_mlm_0.0005_masking ~~.pbtxt and ft_cc.0.0002.pbtxt Are they right?I tried to run this code, but some files are missing (ex. resnet_v1 model,  [VBertFtOffline.ext] 
I hope to run two pbtxt, Could you do me a favor please? Thank you for uploading your great code! Thank you for your time!
I look forward to your reply.

**Comment by yekeren** [comment]
Will take a look this weekend.
